# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

cache: pip

matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35-django-18
  include:
  - python: "3.4"
    env: TOXENV=py34-django-18
  include:
  - python: "3.3"
    env: TOXENV=py33-django-18
  include:
  - python: "2.7"
    env: TOXENV=py27-django-18
  include:
  - python: "3.5"
    env: TOXENV=py35-django-19
  include:
  - python: "3.4"
    env: TOXENV=py34-django-19
  include:
  - python: "2.7"
    env: TOXENV=py27-django-19
  include:
  - python: "3.5"
    env: TOXENV=py35-django-110
  include:
  - python: "3.4"
    env: TOXENV=py34-django-110
  include:
  - python: "2.7"
    env: TOXENV=py27-django-110

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e TOXENV

after_success:
  - codecov -e TOXENV
