# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeddit', '0003_auto_20170616_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
